// AUTO-GENERATED by apps/server/scripts/dump_sse_payload_types.py — do not edit.
// Single source: agentcore.runtime.events.payloads (pydantic wire models; factories in
// runtime/events/*.py remain the only construction path).
// Regenerate: pnpm gen:types  (or uv run python scripts/dump_sse_payload_types.py)

import type { SSEEventType } from "./eventTypes.generated";

export type { SSEEventType } from "./eventTypes.generated";

export interface SSEEvent<T = unknown> {
  type: SSEEventType;
  timestamp: string;
  payload: T;
}

export interface MessageStartPayload {
  message_id: string;
  conversation_id: string;
  /** The turn's log correlation id (32-hex), for one-step log lookup. Omitted when the turn ran without a trace context (e.g. conformance vectors built outside a turn). */
  trace_id?: string;
  /** This frame opens a FULL REPLAY of the turn (an attach catch-up segment), not a live turn: the client MUST reset the local streaming state it holds for this `message_id` (streamed content / reasoning / process timeline) and then fold the frames that follow as the turn's whole story. Absent (or false) on a live first frame and on a repeated same-id stamp, which stay「同回合重开」(keep the bubble). The instruction is the server's — clients must not infer it by comparing the id against whatever bubble is on screen. */
  full_replay?: boolean;
}

export interface ContentDeltaPayload {
  delta: string;
  /** This frame carries the COMPLETE current text of the channel's last still-open text block, not an increment: fold it by REPLACING that block (recomputing the scalar) instead of appending. Absent on live frames and on plain incremental deltas. When the channel's tail is not an open text block (a tool / marker step closed it), the frame folds as an ordinary new block. */
  replace?: boolean;
}

/** Why a `content_reset` / `run_output_reset` fired. Every reason clears
 * the streamed draft and leaves no process trace:
 * `finish_guard`（交付前结构核验回炉）· `retry`（LLM 流式透明重试）·
 * `soft_gate`（captain 软门控打回）· `narration`（worker 旁白回滚）·
 * `ask_user`（blocking ask_user 吸收）. */
export type ResetReason =
  | "finish_guard"
  | "retry"
  | "soft_gate"
  | "narration"
  | "ask_user";

/** 清空当前流式气泡已累积正文的信号——客户端清正文后再接收重写版 `content_delta`。
 * ``reason`` 表明本次 reset 的语义（见 `ResetReason`）；所有 reason 都只清正文、
 * 不折过程痕迹。Transport-only。 */
export interface ContentResetPayload {
  reason: ResetReason;
}

export interface ReasoningDeltaPayload {
  delta: string;
  /** This frame carries the COMPLETE current text of the channel's last still-open text block, not an increment: fold it by REPLACING that block (recomputing the scalar) instead of appending. Absent on live frames and on plain incremental deltas. When the channel's tail is not an open text block (a tool / marker step closed it), the frame folds as an ordinary new block. */
  replace?: boolean;
}

/** The CEO captain is composing a tool call's ARGUMENTS (bubble-scoped twin of
 * `RunToolProgressPayload`). Transport-only liveliness: never journaled. */
export interface ToolProgressPayload {
  tool_name: string;
  chars: number;
}

/** A running tool's coarse EXECUTION phase (工具执行阶段进度). Known values:
 * web_search → queued / querying / fallback; read_url → fetching / reading /
 * blocked; code_execute / test_run → executing; git → git_queued (waiting behind
 * another write on the same repo) / git_credentials (PAT / gh token lookup) /
 * git_remote (push·pull·fetch network leg, create_pr's GitHub REST) / executing
 * (local git command). Kept as a widened `string` on the wire so the backend can
 * add phases without a client bump — an unknown value maps to a generic「处理中」. */
export type ToolPhase =
  | "queued"
  | "querying"
  | "fallback"
  | "fetching"
  | "reading"
  | "executing"
  | "blocked"
  | "git_queued"
  | "git_credentials"
  | "git_remote";

/** A running tool reported an EXECUTION phase — emitted between `tool_use_start` and
 * `tool_use_end` so the waiting UI shows a live, honest state instead of a bare spinner.
 * Transport-only: NEVER journaled and NEVER folded into the process timeline. May carry
 * extra tool-specific keys (e.g. code_execute output streaming `stream`/`chunk`). */
export interface ToolUseProgressPayload {
  tool_call_id: string;
  tool_name: string;
  phase: string;
  /** Present for a delegated worker's call. */
  run_id?: string;
}

export interface ToolUseStartPayload {
  tool_call_id: string;
  tool_name: string;
  arguments: Record<string, unknown>;
  /** Present (run id) when a DELEGATED WORKER raised this call — process folds skip a tagged call (it belongs to that worker's run node, not the CEO's timeline). Absent for the captain's own calls. */
  run_id?: string;
}

/** A tool's OPTIONAL render-oriented payload (工具结果富渲染), distinct from the
 * model-facing `result` text. Opaque on the wire (snake_case). */
export type ToolDisplay = Record<string, unknown>;

/** User-facing tool face on `tool_use_end` when status is error or redirect.
 * `message` = Chinese product copy; `code` = stable code.
 * Model-facing technical detail stays in `result`. */
export interface ToolFailure {
  message: string;
  code: string;
}

export interface ToolUseEndPayload {
  tool_call_id: string;
  tool_name: string;
  result: string;
  status: "success" | "error" | "redirect";
  /** A tool's OPTIONAL render-oriented payload (工具结果富渲染), distinct from the model-facing `result` text. */
  display?: ToolDisplay | null;
  /** Present when status is error or redirect: Chinese product message + stable code. Model-facing technical text stays in result. */
  failure?: ToolFailure;
  /** Worker-call tag; absent for the captain's own calls. */
  run_id?: string;
  /** Delegate batch finished with FAILED/SKIPPED nodes (tool meta ``partial_failure``). Absent when false / non-delegate. */
  partial_failure?: boolean;
  /** CEO-only tool output (coordination host echo / orchestration). User-bubble writers refuse it. Absent for user-salvageable results (blocking delegate synthesis). */
  audience?: "ceo";
}

/** One step in a turn's 思考·正文·工具·协作 inline timeline (统一团队时间线).
 * reasoning/content + tool are the CEO bubble's own narrative; the rest
 * are POSITIONAL MARKERS — zero-width anchors fixing WHERE a non-text element
 * renders (payload looked up from the turn's side channels by id). */
export type ProcessStep =
  | { kind: "reasoning"; text: string }
  | { kind: "content"; text: string }
  | { kind: "tool"; id: string; tool_name: string; arguments: Record<string, unknown>; result: string | null; status: "running" | "success" | "error" | "redirect"; display?: ToolDisplay | null; failure?: ToolFailure; phase?: ToolPhase }
  | { kind: "team"; execution_id: string }
  | { kind: "graph_append"; execution_id: string; host_message_id: string; added_count: number }
  | { kind: "checkpoint"; checkpoint_id: string }
  | { kind: "plan_review"; checkpoint_id: string }
  | { kind: "escalation"; escalation_id: string }
  | { kind: "approval"; approval_id: string }
  | { kind: "stage_card"; stage_card_id: string }
  | { kind: "user_interjection"; interjection_id: string };

/** The user's settlement of a paused GRANTABLE tool call; mirrors the backend
 * `ApprovalDecision`. */
export type ApprovalDecision =
  | "approve"
  | "approve_always"
  | "approve_always_files"
  | "deny"
  | "orphaned";

export interface ApprovalRequiredPayload {
  approval_id: string;
  conversation_id: string;
  tool_call_id: string;
  tool_name: string;
  arguments: Record<string, unknown>;
}

export interface ApprovalResolvedPayload {
  approval_id: string;
  tool_call_id: string;
  decision: ApprovalDecision;
}

/** The user's settlement of a checkpoint the CEO raised (ask_user). */
export type CheckpointDecision =
  | "continue"
  | "adjust"
  | "stop"
  | "research_first"
  | "timeout"
  | "orphaned";

export interface AskAssumption {
  id: string;
  label: string;
  value: string;
}

/** One selectable answer to a choice AskQuestion. `label` is both the displayed text
 * and the value composed back into the answer. Tendency lives in the name
 * (``（推荐）`` / ``(recommended)``), not a separate flag; the card does not pre-select.
 * `action` marks an option that the desktop client fulfils with a
 * native client action instead of a plain text answer (unknown/absent → plain option):
 * `open_local_project` / `register_local_project` / `bind_local_folder` are
 * **本机传统** wire enums（合法非默认；云协作仍推荐「导入到云」；远程仓「从 Git 克隆」；≠离线；
 * 勿当默认主推；``create_folder`` 仍只建云）；
 * `grant_organize_folder` confirms organize-mode (move/copy/mkdir/trash-delete);
 * `grant_attach_folder` confirms attach_rw (本机传统：该根可写可覆盖);
 * still requires explicit user confirm (not silent).
 * For ``grant_*`` only: optional ``well_known`` (``desktop`` / ``downloads`` /
 * ``documents``) and optional ``target_name`` (short basename, no path separators)
 * resolve on the desktop with **no** system folder picker — failure is structured
 * not_found / not_directory / ambiguous (never picker fallback). Optional ``path``
 * may carry an absolute directory hint for organize confirm (mount-only transport
 * exception; success surfaces never return abs).
 * Structured ``op`` / ``source`` / ``destination`` / ``path`` fields also carry
 * organize_plan items for plan-bound ``file_batch``. ``review_kind`` / ``body`` /
 * ``slug`` / ``section`` carry daily_review proposals for server-side apply on
 * confirm. */
export interface AskOption {
  label: string;
  detail?: string;
  action?: "open_local_project" | "register_local_project" | "bind_local_folder" | "grant_organize_folder" | "grant_attach_folder";
  /** 仅 grant_*：常见目录提示；桌面解析直授，失败明确报错（无 picker 兜底）。 */
  well_known?: "desktop" | "downloads" | "documents";
  /** 仅 grant_*：子目录名模糊词（无路径分隔符）；与 well_known 合用尽量唯一匹配。 */
  target_name?: string;
  op?: "move" | "copy" | "delete" | "mkdir";
  source?: string;
  destination?: string;
  path?: string;
  review_kind?: "preference" | "profile" | "topic" | "rule" | "doc";
  body?: string;
  slug?: string;
  section?: string;
}

export interface AskQuestion {
  id: string;
  prompt: string;
  kind: "choice" | "text";
  options: AskOption[];
  multiple: boolean;
  default: string;
}

export type CheckpointIntent = "decision" | "organize_plan" | "daily_review";

/** The CEO paused the turn on an ask_user checkpoint (blocking). */
export interface CheckpointRequiredPayload {
  checkpoint_id: string;
  conversation_id: string;
  question: string;
  assumptions: AskAssumption[];
  questions: AskQuestion[];
  intent?: CheckpointIntent;
  /** true=CEO 请求用户在右坞浏览器完成登录（同 escalate browser_login 体验）。旧流缺字段按 false。 */
  browser_login?: boolean;
}

export interface CheckpointResolvedPayload {
  checkpoint_id: string;
  decision: CheckpointDecision;
  note: string;
  selected?: string[];
}

export interface PlanReviewStep {
  run_id: string;
  role: string;
  summary: string;
}

export interface PlanReviewPending {
  run_id: string;
  role: string;
}

/** 主 Agent 在 plan_review 前对本波产出的把关摘要
 * （拍板卡展示；继续时 llm 压缩注入 gate_notes）。 */
export interface CeoReviewSummary {
  conclusion: string;
  risks: string[];
  suggestions: string[];
  /** 把关来源；旧帧缺省。仅 llm 在 CONTINUE 时压缩注入 gate_notes。 */
  source?: "llm" | "deterministic";
}

export interface PlanReviewRequiredPayload {
  checkpoint_id: string;
  conversation_id: string;
  steps: PlanReviewStep[];
  pending: PlanReviewPending[];
  /** CEO 评审前置把关摘要；旧帧 / 旧向量可缺省。 */
  ceo_review?: CeoReviewSummary;
}

export interface PlanReviewResolvedPayload {
  checkpoint_id: string;
  decision: CheckpointDecision;
  note: string;
}

/** 阶段推进卡（批 B）：命题卡升级为可操作交互；幕 1 收尾后耐久展示。
 * 
 * 信息密度 = 最小决策集：命题 + 双方立场 + 形态/轮次默认 + 嘱咐空位。
 * ``sides`` 复用 motion 卡薄立场；``thorough`` / ``max_rounds`` 为默认展示（卡上不可改）。
 * 可选宿主三元组（机制直传，旧客户端忽略）：开辩锚定幕 1 图。 */
export interface StageCardRequiredPayload {
  stage_card_id: string;
  conversation_id: string;
  motion: string;
  sides: MotionCardSide[];
  form: DebateForm;
  rationale: string;
  fact_pointers?: string[];
  thorough?: boolean;
  max_rounds?: number;
  note?: string;
  /** 幕 1 宿主 execution_id；缺省则开辩时再 resolve_debate_host_attach。 */
  host_execution_id?: string;
  /** 幕 1 汇总员 run_id（挂点锚）。 */
  synthesizer_run_id?: string;
  /** 幕 1 宿主 turn / message id。 */
  host_message_id?: string;
}

/** 推进卡裁决。decision 二值：start_debate（可带 motion_override/note）/ research_first。 */
export interface StageCardResolvedPayload {
  stage_card_id: string;
  decision: "start_debate" | "research_first";
  note?: string;
  motion_override?: string;
}

export type PlanRevisionKind = "bind" | "steer";

export interface PlanRevision {
  run_id: string;
  kind: PlanRevisionKind;
}

export interface PlanRevisedPayload {
  execution_id: string;
  revisions: PlanRevision[];
}

export interface PlanAgentPayload {
  id: string;
  role: string;
  thinking: boolean;
}

export interface RunPlanRunEntry {
  id: string;
  agent_id: string;
  task: string;
  depends_on: string[];
  parent_run_id?: string;
  kind?: RunKind;
  stance?: Stance;
  group?: string;
  round?: number;
  replaces_run_id?: string;
}

export type ActKind = "multi_agent" | "debate";

/** 幕声明（批 A1）：一张 execution 图由 1..N 幕组成；本批仅首幕 act-1。
 * 
 * runs 归属 = 该 run_plan 声明的幕（``RunPlanRunEntry`` 不加字段）。
 * ``authorized_by``（批 B）：辩论幕的授权来源；调研幕缺省。 */
export interface RunPlanAct {
  act_id: string;
  kind: ActKind;
  title?: string;
  anchor_run_id?: string;
  authorized_by?: "stage_card" | "auto" | "preview";
}

export interface RunPlanPayload {
  execution_id: string;
  plan_type: "single_agent" | "multi_agent" | "debate";
  task_summary: string;
  agents: PlanAgentPayload[];
  runs: RunPlanRunEntry[];
  host_message_id?: string;
  prev_execution_id?: string;
  act?: RunPlanAct;
}

/** 已停发：旧跨回合同图追加锚点（兼容旧 journal 回放）。新路径用 prev_execution_id。 */
export interface GraphAppendPayload {
  execution_id: string;
  host_message_id: string;
  append_message_id: string;
  added_count: number;
  roles?: string[];
  added_run_ids?: string[];
  act_id?: string;
  act_kind?: ActKind;
  authorized_by?: "stage_card" | "auto" | "preview";
}

export type RunKind = "captain" | "agent";

export type Stance = "pro" | "con";

export interface RunStartedPayload {
  run_id: string;
  agent_id: string;
  parent_run_id: string | null;
  kind: RunKind;
  continues_run_id?: string;
  stance?: Stance;
  group?: string;
  round?: number;
  side_key?: string;
  replaces_run_id?: string;
}

export interface ContextBlockWire {
  channel: "system" | "history" | "request" | "team_position" | "dependency" | "workspace" | "task" | "deliverable" | "team_brief" | "gate_notes" | "steer" | "team_result" | "round_focus" | "opponent" | "challenge" | "interjection" | "continuation" | "cross_exam" | "witness_exam" | "closing" | "attack" | "defense" | "rebuttal" | "thread" | "crux";
  heading: string;
  body: string;
  chars: number;
  truncated: boolean;
  source_role: string;
  source_run_id: string;
  fidelity: "" | "pointer" | "summarize" | "pass_through";
  files: string[];
}

export interface RunContextPayload {
  run_id: string;
  agent_id: string;
  blocks: ContextBlockWire[];
}

export interface RunOutputDeltaPayload {
  run_id: string;
  agent_id: string;
  delta: string;
  /** This frame carries the COMPLETE current text of the channel's last still-open text block, not an increment: fold it by REPLACING that block (recomputing the scalar) instead of appending. Absent on live frames and on plain incremental deltas. When the channel's tail is not an open text block (a tool / marker step closed it), the frame folds as an ordinary new block. */
  replace?: boolean;
}

export interface RunOutputResetPayload {
  run_id: string;
  agent_id: string;
  reason: ResetReason;
}

export interface RunReasoningDeltaPayload {
  run_id: string;
  agent_id: string;
  delta: string;
  /** This frame carries the COMPLETE current text of the channel's last still-open text block, not an increment: fold it by REPLACING that block (recomputing the scalar) instead of appending. Absent on live frames and on plain incremental deltas. When the channel's tail is not an open text block (a tool / marker step closed it), the frame folds as an ordinary new block. */
  replace?: boolean;
}

export interface RunToolProgressPayload {
  run_id: string;
  agent_id: string;
  tool_name: string;
  chars: number;
}

export type WorkerRunPhase =
  | "thinking"
  | "tool"
  | "waiting_children"
  | "winding_down";

/** Worker 活动相位（``run_phase``）：等 LLM / 跑工具 / 等子 / 超时·token 收尾。
 * 
 * EPHEMERAL——传输态；``tool_name`` 仅 ``phase=tool`` 时有意义。``winding_down``
 * 在投影侧粘性覆盖 thinking/tool，直到 run 终态。 */
export interface RunPhasePayload {
  run_id: string;
  agent_id: string;
  phase: WorkerRunPhase;
  tool_name?: string;
}

export type EscalationKind = "normal" | "scope" | "dep";

export type RunFailureKind =
  | "quality"
  | "format"
  | "model"
  | "call";

/** 升级实时可见 (非阻塞 raised): a worker flagged a decision/blocker and kept working.
 * 
 * JOURNALED (DURABLE, 统一时间线二期 D6): ``escalation_id`` keys the raised 轻行's
 * timeline marker (幂等去重 on attach replay) and lets the raised row + node ⚠️ badge
 * reload — the event base is now level with ``escalation_required``.
 * 
 * ``source`` distinguishes early-stop / thrashing backstops (``validation_thrash`` /
 * ``ceiling_backstop``) from genuine mid-work escalate (omit / absent). */
export interface RunEscalationPayload {
  escalation_id: string;
  run_id: string;
  agent_id: string;
  question: string;
  assumption: string;
  blocking: boolean;
  kind?: EscalationKind;
  source?: string;
}

export interface RunEscalationGatePayload {
  run_id: string;
  agent_id: string;
  layer: "execution" | "scheme";
  action: "continue" | "escalate";
  signals: Record<string, unknown>[];
}

/** 阻塞式求决策 (escalate blocking=true): a delegated worker SUSPENDED itself awaiting
 * a decision. JOURNALED (unlike the transport-only `run_escalation` banner); the
 * turn never flips to `paused` (siblings keep running).
 * 
 * ``awaiting``: ``user`` (经典路径，可答卡) or ``ceo`` (协调模式下等主管仲裁，初始不可答)。
 * Absent on old journaled events → fold as ``user``. */
export interface EscalationRequiredPayload {
  escalation_id: string;
  run_id: string;
  agent_id: string;
  question: string;
  assumption: string;
  /** Structured forks (同 ask_user 的 questions). Absent on old journaled events (fold with `?? []`); empty for a free-text ask. */
  questions?: AskQuestion[];
  /** 旧流缺字段时前端按 `normal`。与 blocking 轴正交。 */
  kind?: EscalationKind;
  /** 谁在仲裁：user=经典可答卡；ceo=协调模式等主管。旧流缺字段按 user。 */
  awaiting?: "user" | "ceo";
  /** true=用户可在回合仍 running 时接管浏览器完成登录（D16 窄例外）。旧流缺字段按 false。 */
  browser_login?: boolean;
  /** 写权冲突路径列表；有值时前端呈现「移交写权 / 保持原主」。旧流缺字段按无。 */
  ownership_paths?: string[];
  /** 当前写权持有者 run_id。旧流缺字段按无。 */
  lock_owner_run_id?: string;
  /** 本次挂起的墙钟上限（秒）——仅运维配了 checkpoint_timeout_seconds 才有值，届时回落 assumption 发 timed_out。缺省 = 默认的无限期等待（D2）：不答就不会自动继续。卡面文案据此二选一，不得无条件承诺「未答则按假设继续」。 */
  timeout_seconds?: number;
}

/** 阻塞式求决策 settlement. Emitted by the suspending tool's awaiter ONLY; journaled.
 * 
 * ``status`` 三分（对 worker 回落假设的实现可共享，对外语义必须分开）：
 * - ``resolved`` — 有裁决/答复（``answer`` 非空语义由调用方保证）
 * - ``assumed`` — 用户或主管显式选了「按假设继续」
 * - ``timed_out`` — 墙钟时限内未答复
 * 
 * ``arbitrated_by`` / ``via_user`` annotate CEO 协调仲裁可见性（经典用户直答路径可缺省）。 */
export interface EscalationResolvedPayload {
  escalation_id: string;
  run_id: string;
  agent_id: string;
  status: "resolved" | "assumed" | "timed_out" | "orphaned";
  answer: string;
  /** 裁决方：user=用户直答；ceo=主管仲裁。旧流缺字段按 user。 */
  arbitrated_by?: "user" | "ceo";
  /** 仅 arbitrated_by=ceo 时有意义：true=主管经 ask_user 转交用户后再 resolve。 */
  via_user?: boolean;
}

/** pending 交互失效（假卡消灭）。含热路 kind + 推进卡 stage_card。 */
export interface InteractionOrphanedPayload {
  interaction_id: string;
  kind: "approval" | "escalation" | "debate_round" | "stage_card";
  /** 可选失效原因（如 stage_card superseded）；缺省不传，旧客户端忽略。 */
  reason?: string;
}

export interface TeamSynthesisWorkerPreview {
  run_id: string;
  role: string;
  status: "pending" | "completed" | "failed" | "cancelled";
  summary: string;
}

export interface TeamSynthesisPreviewPayload {
  execution_id: string;
  completed: number;
  total: number;
  headline: string;
  text: string;
  workers: TeamSynthesisWorkerPreview[];
  in_progress: boolean;
}

/** CEO 协调等待（``coordination_wait``）：captain 空等团队事件时的前端 UX 信号。
 * 
 * ``waiting=true`` 进入/心跳刷新；``waiting=false`` 清除。``completed``/``total`` 为
 * session 计数（已完成 worker / 总 worker）。EPHEMERAL——不落 journal。 */
export interface CoordinationWaitPayload {
  execution_id: string;
  waiting: boolean;
  completed: number;
  total: number;
}

/** 同 folder 写锁短等（``workspace_lock_wait``）：跨会话串行时的前端 UX 信号。
 * 
 * ``waiting=true`` 即将阻塞在 ``workspace_lock``；``waiting=false`` 已拿到锁。
 * 与同对话 FIFO ``turn_queued`` 正交。EPHEMERAL——不落 journal。 */
export interface WorkspaceLockWaitPayload {
  conversation_id: string;
  waiting: boolean;
}

/** Overall verdict of a delegate batch's delivery reconciliation (交付诚实性):
 * delivered = 无缺口且有落盘产物; partial = 有产物也有缺口; blocked = 有缺口且
 * 无落盘产物. */
export type DeliveryState =
  | "delivered"
  | "partial"
  | "blocked"
  | "notes";

/** One undelivered piece in the wrap-up reconciliation (交付诚实性): the worker
 * ``role`` it belongs to (or a batch-level label like「验收」) + a one-line
 * ``description`` of what never landed (contract shortfall / degraded handoff /
 * completion criteria unmet / failed worker).
 * 
 * Optional ``reason`` is a machine-readable cutoff / shortfall code when the gap
 * comes from a structured engine signal — known:
 * ``token_budget`` / ``worker_timeout`` / ``max_rounds`` / ``degraded_handoff`` /
 * ``unverified_note`` (soft 示例/虚构自注；不单独把 state 打成 notes) /
 * ``files_not_landed`` (零落盘 soft tip：per-worker「本队员本波未交卷」/
 * 批次「本批未见落盘」；甲⁺ 起不挡收工) /
 * ``verify_failed`` (验证形工具失败：browser navigate / test_run /
 * verify 形 code_execute·terminal).
 * Absent for ordinary contract / criteria prose gaps that have not been projected.
 * Clients may badge known codes and ignore unknown ones (forward-compatible).
 * 
 * Optional ``severity``: ``warning`` = soft reminder (待核实等，不单独撑起
 * partial/blocked); absent or ``blocking`` = real shortfall. Old clients that
 * ignore unknown fields still see the row; new clients split summary / card state.
 * 
 * Optional ``paths``: workspace-relative files implicated by a soft note (for
 * 「打开相关文件」); absent on ordinary blocking gaps. */
export interface DeliveryGap {
  role: string;
  description: string;
  reason?: string;
  severity?: "blocking" | "warning";
  paths?: string[];
}

/** One user action that would close a delivery gap. ``kind`` is a widened string
 * on the wire (like ``ToolPhase``) so the backend can add kinds without a client
 * bump — known: ``bind_local_folder`` (wire kind；产品文案按会话分流：
 * 工程尚在本机 → 云协作「导入到云」优先；远程仓进当前云桌走 git clone /
 * Composer「从 Git 克隆」；**已是云端会话但沙箱未装配** →
 * 禁止再导「导入到云」，改稍后重试 / export_to_local / 本机传统；
 * 本机传统合法非默认，≠离线)；
 * ``export_to_local`` (云端已有 delivered_files → 导出到本机文件夹后即可 npm install / 本地运行；
 * 与 bind_local_folder 可并存但语义不同);
 * ``website_verify`` (legacy tape only — runtime 已停发整页 QA 续派按钮);
 * ``continue_skipped_runs`` (turn/nested 额度 SKIPPED 未跑节点 → 下一回合续跑);
 * unknown kinds render as a plain hint.
 * （成篇未写完改由对话框接着说——已撤 ``continue_writing`` 一键按钮。）
 * 
 * Optional ``prompt`` is the exact user-turn text a client should send for
 * kinds that open a new message (e.g. ``continue_skipped_runs``; old
 * ``website_verify`` tapes still carry one). Absent for
 * non-message actions like ``bind_local_folder`` / ``export_to_local``. */
export interface DeliveryAction {
  kind: string;
  description: string;
  prompt?: string;
}

/** One path-level acceptance row on ``delivery_status`` (主清单数据源).
 * 
 * ``status=accepted`` → counts toward ``delivered_files`` / CEO「已交付」;
 * ``rejected`` carries ``reason`` (e.g. ``citations_unverified`` / ``run_failed``)
 * and optional ``detail`` for the file checklist. Undeclared extras are omitted
 * (not rejected). Draft is out of scope for block 1.
 * ``workspace_id``: landing desk when the plan node set ``target_folder_id``
 * (``folder:{id}``); omit → client falls back to the session birth desk.
 * 
 * ``kind`` / ``derived_from`` are the producing tool's OWN self-report
 * (``tools/file_products.py``), carried verbatim from the run-level ledger:
 * ``kind`` is the normalized product type (``md`` / ``docx`` / ``pdf`` / ``code``
 * / ``image`` / ``file`` …); ``derived_from`` names the source this product was
 * EXPORTED from (``md_to_docx``: docx ← 源 md), so a client can demote that source
 * to 中间稿 the same way ``fold_exported_sources`` does server-side. Absent when the
 * producer did not self-report — clients must NOT guess lineage from extensions or
 * tool names, and must keep every accepted path reachable (fold ≠ drop). */
export interface DeliveryArtifact {
  path: string;
  status: "accepted" | "rejected";
  reason?: string;
  detail?: string;
  workspace_id?: string;
  kind?: string;
  derived_from?: string;
}

/** Historical ``delivery_status.promoted`` row（AI 工作间 → 用户工作区）.
 * 
 * ``promote_product`` 已撤销；本结构只兼容旧事件。``from`` 是当时的旧路径，``to``
 * 是搬走后的位置。空数组是合法状态（字段缺省即空）。 */
export interface DeliveryPromotion {
  /** AI 工作间旧路径（已不存在） */
  from: string;
  /** 用户工作区新路径（现在的位置） */
  to: string;
}

/** 交付状态（能力闸门与交付诚实性）: the structured delivery reconciliation a
 * delegate batch emits at wrap-up — 已交付文件 / 缺口 / 待用户操作 — so the client
 * renders an honest delivery card instead of mining the CEO's prose.
 * Folds keep the LATEST per ``execution_id`` (the event already unions
 * declared-and-landed paths across hops of that execution).
 * ``state``: delivered = 无 blocking 缺口且有落盘产物; partial = 有产物也有
 * blocking 缺口; blocked = 有 blocking 缺口且无落盘产物;
 * notes = 仍有 soft 提醒且非「仅 unverified_note」（轻提醒，非「部分未满足」）；
 * 声明路径未落盘为 path_mismatch blocking gap，不得 delivered；未声明落盘不进
 * ``artifacts``。
 * ``artifacts``: path-level acceptance (accepted+rejected) for declared landings;
 * ``delivered_files`` remains accepted-only for older clients.
 * ``promoted``: 历史 ``{from, to}`` 归位行（``promote_product`` 已撤销；新回合不再写入）。
 * 旧卡 journal 重放仍带此字段；无归位时缺省（= 空数组）。 */
export interface DeliveryStatusPayload {
  execution_id: string;
  state: DeliveryState;
  summary: string;
  delivered_files: string[];
  gaps: DeliveryGap[];
  actions: DeliveryAction[];
  artifacts?: DeliveryArtifact[];
  promoted?: DeliveryPromotion[];
}

/** Attachment metadata on a mid-flight interjection (no inline text body). */
export interface UserInterjectionAttachment {
  name: string;
  workspace_path?: string;
  binary?: boolean;
}

/** Soft @Agent chip on a mid-flight interjection (prompt hint, not a hard route). */
export interface UserInterjectionAgentMention {
  agent_id: string;
  role: string;
}

/** Mid-flight user interjection into a live turn (经典 steer + 协调插话共用).
 * 
 * Lifecycle:
 * - 协调: ``received`` → ``injected`` → ``addressed`` / ``queued`` / ``failed``
 * - 经典: ``received`` → ``injected`` (终态) / ``queued`` / ``failed``（无 ``addressed``）
 * ``injected`` = 内容真正写入模型上下文的那一刻。 */
export interface UserInterjectionPayload {
  interjection_id: string;
  execution_id: string;
  content: string;
  status: "received" | "injected" | "addressed" | "queued" | "failed";
  note?: string;
  attachments?: UserInterjectionAttachment[];
  agent_mentions?: UserInterjectionAgentMention[];
}

/** FIFO queue ack on the send SSE while another turn is in-flight (D9 · 发送即有流).
 * 
 * Replaces the retired HTTP 202 ``SendMessageQueuedResponse`` JSON. Same visibility
 * fields; the waiting connection later continues with the drained turn on this stream.
 * ``degraded_from=steer`` when the client asked for steer but soft-insert was
 * unavailable (无 live accepting 窗口 / 回合已收口；协调插话路径不会带此字段). */
export interface TurnQueuedPayload {
  queue_id: string;
  position: number;
  queue_depth: number;
  conversation_id: string;
  degraded_from?: "steer";
}

/** Same fields as REST ``QueuedTurnItem`` / send-turn ``MessageAttachment``.
 * 
 * Nested on ``turn_queue_started`` so the timeline entrance frame is self-describing
 * (not the thinner ``UserInterjectionAttachment``). */
export interface MessageAttachment {
  name: string;
  path: string;
  text?: string;
  truncated?: boolean;
  kind?: "file" | "dir" | "conversation" | "document";
  conversation_id?: string | null;
  document_id?: string | null;
  binary?: boolean;
  workspace_path?: string | null;
}

/** Same fields as REST ``QueuedTurnItem.agent_mentions`` / ``AgentMention``. */
export interface AgentMention {
  agent_id: string;
  role: string;
}

/** FIFO dequeue → timeline user-bubble entrance (D9 · 发送即有流).
 * 
 * Emitted as the **first frame** of the drained turn's EventSink (after ``pop_next``,
 * before ``stream_chat`` / ``message_start``). ``content`` is the queued user text
 * (on the frame — not persist-first). Empty ``attachments`` / ``agent_mentions`` are
 * absent. ``remaining_depth`` is the queue length after this item left the FIFO.
 * EPHEMERAL — reload 靠 REST; 不落 journal. */
export interface TurnQueueStartedPayload {
  queue_id: string;
  conversation_id: string;
  remaining_depth: number;
  content: string;
  attachments?: MessageAttachment[];
  agent_mentions?: AgentMention[];
}

/** Per-item queue cancel ack (同对话再发 · drain 前取消). EPHEMERAL — multi-client UI clear. */
export interface TurnQueueCancelledPayload {
  queue_id: string;
  conversation_id: string;
}

/** Cold resume deferred while a live turn holds the slot. EPHEMERAL — same-connection wait.
 * 
 * Settlement is already prewritten; claim + continuation start after the slot frees.
 * ``busy_reason=wrap_up`` when the live sink is still this ``message_id`` (host winding
 * down); ``live_turn`` when another turn occupies the conversation slot. */
export interface ResumeDeferredPayload {
  message_id: string;
  conversation_id: string;
  busy_reason: "wrap_up" | "live_turn";
}

/** Cold resume that found its frame already consumed. EPHEMERAL — idempotent success.
 * 
 * The conclusion is durable in ``paused_turn_outcomes``, stamped by whoever won the
 * atomic claim on the paused frame; this frame relays THAT decision — which card
 * (``kind`` + ``checkpoint_id``), what was decided (``decision``) and when
 * (``decided_at``) — never the decision the caller itself just submitted.
 * 
 * ``turn_status`` answers a separate question: where the TURN stands (the assistant
 * row's ``usage.status``), so a client knows whether to close out its streaming
 * bubble. ``running`` means the continuation is still going and the bubble stays
 * open; this connection then carries its stream when the run is on this server. */
export interface ResumeSettledPayload {
  message_id: string;
  conversation_id: string;
  kind: "ask_user" | "plan_review";
  checkpoint_id: string;
  decision: string;
  decided_at: string;
  turn_status: "running" | "complete" | "incomplete" | "failed" | "unknown";
}

/** 执行转后台（``execution_detached``）：附着回合已收口，团队继续跑。 */
export interface ExecutionDetachedPayload {
  execution_id: string;
  conversation_id: string;
  completed: number;
  total: number;
  reason?: string;
  host_turn_id?: string;
}

/** 后台执行终态（``execution_completed``）：drive 到齐、收割者可发起收口。 */
export interface ExecutionCompletedPayload {
  execution_id: string;
  conversation_id: string;
  completed: number;
  total: number;
  status?: "completed" | "failed" | "cancelled";
  host_turn_id?: string;
  error?: string;
}

/** Token counts in the ledger short-key form. `cache_hit + cache_miss === input`. */
export interface UsageBreakdown {
  input: number;
  output: number;
  reasoning: number;
  cache_hit: number;
  cache_miss: number;
}

/** A run's / turn's cost in integer nano-money (1 unit = 1e9).
 * 
 * ``currency`` labels ``input``/``cached``/``output``/``total`` — curated CNY or
 * community-estimated USD, never converted (this product has no FX). Clients
 * must read it to pick a symbol; inferring ¥ from ``pricing_source`` is how BYOK
 * dollars once rendered as yuan at ~1/7 of the real amount. */
export interface CostBreakdown {
  input: number;
  cached: number;
  output: number;
  total: number;
  currency: string;
  pricing_source?: string;
  estimated_total?: number;
  estimated_currency?: string;
}

/** 辩论形态成员集单源（``runtime.debate.types.DebateForm``）；wire / schema / 标签键同集。 */
export type DebateForm = "debate" | "red_team" | "roundtable";

/** One participant on a handoff ``motion_card`` (thin stance, not an argument list). */
export interface MotionCardSide {
  key: string;
  name: string;
  stance: string;
}

/** Worker-authored「建议开辩」命题卡 — optional on ``RunDebrief``; omitted when absent. */
export interface MotionCard {
  motion: string;
  sides: MotionCardSide[];
  fact_pointers: string[];
  rationale: string;
  form: DebateForm;
}

/** 完工交接简报 — every field optional; absent when the worker did not call `handoff`. */
export interface RunDebrief {
  summary?: string | null;
  key_points?: string[] | null;
  assumptions?: string | null;
  next_steps?: string | null;
  motion_card?: MotionCard;
}

export interface RunCompletedPayload {
  run_id: string;
  agent_id: string;
  output_summary: string;
  duration_ms: number;
  role: string;
  model: string;
  usage: UsageBreakdown;
  cost: CostBreakdown;
  debrief?: RunDebrief;
  output_files?: string[];
  gaps?: DeliveryGap[];
  execution_id?: string;
}

export interface RunFailedPayload {
  run_id: string;
  agent_id: string;
  error: string;
  failure_kind?: RunFailureKind;
  debrief?: RunDebrief;
  execution_id?: string;
  product_landed?: boolean;
  error_code?: string;
  retryable?: boolean;
  retry_after?: number;
}

export interface RunCancelledPayload {
  run_id: string;
  agent_id: string;
  reason: "redirect" | "stop" | "user_stop" | "worker_timeout";
  execution_id?: string;
}

export interface RunSkippedPayload {
  run_id: string;
  agent_id: string;
  reason: "cascade" | "abort";
}

export interface RunProgressPayload {
  completed: number;
  total: number;
}

export interface NodeTimingPayload {
  run_id: string;
  start_ms: number;
  end_ms: number;
  outcome: string;
}

export interface BatchMetricsPayload {
  execution_id: string;
  nodes: number;
  width: number;
  peak_running: number;
  wall_ms: number;
  busy_ms: number;
  slot_starved: number;
  completed: number;
  failed: number;
  skipped: number;
  cancelled: number;
  bind_boundaries: number;
  scope_boundaries: number;
  checkpoint_boundaries: number;
  escalations: number;
  scope_escalations: number;
  timeline: NodeTimingPayload[];
}

export interface DebateSideInfo {
  key: string;
  name: string;
  stance: string;
  is_subject: boolean;
  /** 该方辩手模型 id。 */
  model?: string;
  /** 付款来源（行属性）。 */
  origin?: "platform" | "byok";
  /** BYOK 服务商 id。 */
  provider_id?: string;
}

/** 辩手发言的一条结构化论点（后端 speech_parse 产出）。 */
export interface DebateSpeechArgument {
  id: string;
  title: string;
  body: string;
}

export interface DebateRoundSide {
  key: string;
  name: string;
  run_id: string;
  ok: boolean;
  absent?: boolean;
  arguments?: DebateSpeechArgument[];
  beat?: "statement" | "attack" | "defense" | "rebuttal" | "thread" | "crux";
}

/** 红队 finding 结构载荷（O2：全文靠 run_id）。 */
export interface DebateFindingInfo {
  id: string;
  severity: "critical" | "major" | "minor";
  target: string;
  attacker_key: string;
  status: "open" | "answered" | "closed" | "escalated" | "deadlocked" | "unanswered";
  disposition?: string;
  attack_run_id?: string;
  response_run_id?: string;
  rebuttal_run_id?: string;
  merged_from?: string[];
}

/** 圆桌线程 turn 结构载荷（O2：全文靠 run_id）。 */
export interface DebateThreadTurnInfo {
  speaker: string;
  reply_to?: string;
  run_id: string;
  ok?: boolean;
  beat?: "thread" | "crux";
}

export interface DebateConsensusMapItem {
  topic: string;
  consensus?: string[];
  divergences?: string[];
  crux?: string;
}

export interface DebateVerdict {
  real_clash: boolean;
  new_arguments: boolean;
  converged: boolean;
  stop_reason: string;
  rationale: string;
}

export interface DebateClash {
  from_key: string;
  to_key: string;
  point: string;
}

export interface DebateUserInterjection {
  ask: string;
  target_key: string;
  answered: boolean;
}

export interface DebateCrossExamExchange {
  question: string;
  answer: string;
}

export interface DebateCrossExam {
  target: string;
  questioner: string;
  exchanges: DebateCrossExamExchange[];
  answer_run_id: string;
}

/** 批 D1 · 证人答问（additive）：主持人点名幕1 透镜证人的事实性问答。 */
export interface DebateWitnessExam {
  witness_key: string;
  lens_run_id: string;
  seat_run_id?: string;
  name: string;
  origin_caption?: string;
  exchanges?: DebateCrossExamExchange[];
  answer_run_id?: string;
}

/** 批 D1 · 本场证人席位花名册条目。 */
export interface DebateWitnessSeat {
  key: string;
  name: string;
  lens_run_id: string;
  seat_run_id: string;
  lens_label?: string;
  origin_caption?: string;
}

export interface DebateClosing {
  key: string;
  name: string;
  run_id: string;
  ok: boolean;
}

export interface DebateRoundScore {
  argument: number;
  engagement: number;
  evidence: number;
  penalties: string[];
  note: string;
  total: number;
}

/** 场级证据台账条目（Citation ⊃ 台账字段 + 登记方 side_key）。
 * 
 * 约定文档预登记（批 D2）可选来源锚：``dossier_path`` / ``origin_id`` / ``dossier_label``；
 * 旧 journal / 旧向量缺字段 → 前端忽略，零回归。 */
export interface EvidenceLedgerEntry {
  id: string;
  url?: string;
  title?: string;
  snippet?: string;
  site?: string;
  date?: string;
  tier?: string;
  side_key?: string;
  dossier_path?: string;
  origin_id?: string;
  dossier_label?: string;
}

/** 回合调研台账条目（辩论 ``EvidenceLedgerEntry`` 超集）。
 * 
 * ``registrant`` ↔ 辩论 ``side_key``。``selected`` / ``doc_kind`` 随 ledger JSON 透传。 */
export interface TurnEvidenceLedgerEntry {
  id: string;
  url?: string;
  title?: string;
  snippet?: string;
  site?: string;
  date?: string;
  tier?: string;
  query?: string;
  deep_read?: boolean;
  selected?: boolean;
  doc_kind?: string;
  registrant?: string;
  citable?: boolean;
}

/** Turn 级台账通道（引用即出处 P1 · Q4）。
 * 
 * - ``delta``：自上次 drain 以来的增量（live mid-turn）
 * - ``entries``：全量快照（settle 权威覆盖；与 delta 可同发，客户端以 entries 为准）
 * - ``cited_ids``：成稿实际引用的 id 集（P2：``citations_event`` 投影权威；通常仅 settle 携带） */
export interface EvidenceLedgerPayload {
  delta?: TurnEvidenceLedgerEntry[];
  entries?: TurnEvidenceLedgerEntry[];
  cited_ids?: string[];
}

export interface DebateRoundInfo {
  round_no: number;
  focus: string;
  summary: string;
  verdict: DebateVerdict;
  sides: DebateRoundSide[];
  clashes: DebateClash[];
  user_interjections?: DebateUserInterjection[];
  cross_exam?: DebateCrossExam[];
  witness_exam?: DebateWitnessExam[];
  scores?: Record<string, DebateRoundScore>;
  evidence_ledger_delta?: EvidenceLedgerEntry[];
  findings?: DebateFindingInfo[];
  thread_turns?: DebateThreadTurnInfo[];
}

export interface DebateNarrativeRound {
  round_no: number;
  focus: string;
  summary: string;
  verdict: DebateVerdict | null;
  sides: DebateRoundSide[];
  clashes: DebateClash[];
  cross_exam: DebateCrossExam[];
  witness_exam?: DebateWitnessExam[];
  findings?: DebateFindingInfo[];
  thread_turns?: DebateThreadTurnInfo[];
}

/** 交接清单条目：按解决路径分类（value / fact / question）。 */
export interface DebateHandoffInfo {
  kind: "value" | "fact" | "question";
  text: string;
}

export interface DebateBriefInfo {
  crux: string;
  strongest_points: Record<string, string>;
  risk_severities?: Record<string, string>;
  findings?: DebateFindingInfo[];
  gate?: string;
  must_fix?: string[];
  consensus_map?: DebateConsensusMapItem[];
  handoffs?: DebateHandoffInfo[];
  decisive?: string;
  leaning: string;
  confidence: string;
  recommendation: string;
}

export interface DebateResultPayload {
  execution_id: string;
  moderator_run_id: string;
  form: DebateForm;
  motion: string;
  stop_reason: string;
  opening?: string;
  narrative_first: boolean;
  sides: DebateSideInfo[];
  rounds: DebateRoundInfo[];
  closings?: DebateClosing[];
  witnesses?: DebateWitnessSeat[];
  brief: DebateBriefInfo;
  evidence_ledger?: EvidenceLedgerEntry[];
  subtopics?: string[];
  /** 裁判模型 id。 */
  moderator_model?: string;
  /** 裁判模型来源。 */
  moderator_origin?: "platform" | "byok";
  /** 裁判 BYOK provider_id。 */
  moderator_provider_id?: string;
  /** 同模型降级明示。 */
  same_model_debate?: boolean;
}

export interface DebateRoundStartedPayload {
  execution_id: string;
  moderator_run_id: string;
  round_no: number;
  focus: string;
  cross_exam_enabled?: boolean;
  opening?: string;
  /** Form signal for live status; absent on older wire. */
  form?: DebateForm;
}

export interface DebateRoundPayload extends DebateRoundInfo {
  execution_id: string;
  moderator_run_id: string;
}

export interface DebatePretrialSideInfo {
  key: string;
  name: string;
}

export interface DebatePretrialTask {
  query: string;
  purpose?: string;
}

export interface DebatePretrialOrder {
  side_key: string;
  tasks?: DebatePretrialTask[];
  source?: "debater" | "auto" | "empty";
}

export interface DebateEvidencePackSource {
  source_id: string;
  kind: "attachment" | "conversation" | "background" | "dossier" | "workspace";
  label: string;
  path?: string | null;
  excerpt?: string;
  complete?: boolean;
  failure?: string | null;
}

export interface DebateEvidencePackDispute {
  claim: string;
  why_contested?: string | null;
  related_source_ids?: string[];
}

/** 共享证据包（庭前附件路径）；完整度一等公民。 */
export interface DebateEvidencePack {
  motion?: string | null;
  completeness?: "full" | "partial" | "empty";
  notes?: string | null;
  sources?: DebateEvidencePackSource[];
  dispute_candidates?: DebateEvidencePackDispute[];
  ledger_ids?: Record<string, string> | null;
}

export interface DebatePretrialStartedPayload {
  execution_id: string;
  moderator_run_id: string;
  thorough?: boolean;
  sides?: DebatePretrialSideInfo[];
  /** Set when pretrial is skipped immediately; absent when phase proceeds. */
  skip_reason?: "fast" | "dossier_sufficient" | "evidence_pack" | "no_pack";
}

export interface DebatePretrialOrdersPayload {
  execution_id: string;
  moderator_run_id: string;
  thorough?: boolean;
  sides?: DebatePretrialSideInfo[];
  orders?: DebatePretrialOrder[];
  /** Present when pretrial takes the shared evidence-pack path. */
  evidence_pack?: DebateEvidencePack;
  /** Present when orders event is emitted for the evidence-pack path. */
  path?: "evidence_pack";
  /** Evidence completeness when path=evidence_pack*. */
  completeness?: "full" | "partial" | "empty";
  /** True when completeness is not full (evidence-pack path). */
  incomplete?: boolean;
  /** External-evidence plan (mode=skip + reason/budget); production emits skip only. */
  external_evidence?: Record<string, unknown>;
}

export interface DebatePretrialCompletedPayload {
  execution_id: string;
  moderator_run_id: string;
  thorough?: boolean;
  sides?: DebatePretrialSideInfo[];
  status?: "done" | "skipped" | "degraded";
  /** Present when status=skipped. */
  skip_reason?: "fast" | "dossier_sufficient" | "evidence_pack" | "no_pack";
  orders?: DebatePretrialOrder[];
  fallback_self_search?: boolean;
  evidence_ready?: boolean;
  evidence_ledger_count?: number;
  evidence_ledger_delta?: EvidenceLedgerEntry[];
  completeness?: "full" | "partial" | "empty";
  incomplete?: boolean;
  /** Present when pretrial assembled a shared evidence pack from host attachments. */
  evidence_pack?: DebateEvidencePack;
  /** Resolved external-evidence mode; production emits skip only. */
  external_evidence_mode?: "skip";
  /** Skip reason: evidence_pack_full | evidence_pack_partial | no_pack | fast | … */
  external_evidence_reason?: string;
}

/** 协作质量: turn-level orchestration signals for 诊断模式. Omitted on single-agent
 * turns and legacy streams. */
export interface TurnCollabMetrics {
  boundary_yields: number;
  scope_signals: number;
  revises: number;
  escalations: number;
  /** 审计采集降级计数 (turn_metrics.audit_drops); 诊断模式 only. */
  audit_drops?: number;
  /** boundary_yields 中由用户拍板造成的那部分 (plan_review checkpoint)。 */
  boundary_yields_by_user?: number;
  /** revises 中由用户「立即改此人」促成的那部分 (redirect 热修)。 */
  revises_by_user?: number;
}

/** 本回合团队状态（turn journal 派生）：no_batch / in_flight / settled。
 * 没派工是确定态，不是信息缺失。worker_count = 本波 kickoff 编制，不含 captain。 */
export type TeamBatchStatus =
  | { kind: "no_batch" }
  | { kind: "in_flight"; worker_count: number }
  | { kind: "settled"; worker_count: number };

/** Turn token totals (long-key form, contrast `UsageBreakdown` short keys on runs). */
export interface MessageEndUsage {
  input_tokens: number;
  output_tokens: number;
  reasoning_tokens: number;
  cache_hit_tokens: number;
  cache_miss_tokens: number;
}

/** Terminal turn event. `finish_reason=paused` = 挂起即收口: the turn finalized AT a
 * durable checkpoint and awaits POST .../resume — NOT done and not aborted. */
export interface MessageEndPayload {
  finish_reason: "end_turn" | "max_rounds" | "degraded" | "unproductive" | "error" | "cancelled" | "interrupted" | "paused";
  usage?: MessageEndUsage;
  cost?: CostBreakdown;
  rounds?: number;
  collab?: TurnCollabMetrics;
  /** 本回合团队状态（turn journal 派生）。没派工是 no_batch，不是缺字段。 */
  team_batch?: TeamBatchStatus;
  duration_ms?: number;
  /** Turn-level result quality, independent of finish_reason. partial = landed product with gaps. paused is reserved (not produced this wave). */
  outcome?: "ok" | "partial" | "paused" | "error";
}

export interface ErrorContext {
  upstream_status?: number;
  upstream_body_preview?: string | null;
  retry_attempts?: number;
  empty_diagnosis?: string;
  /** empty-response body class: html | json | text | empty (no raw HTML). */
  body_kind?: string;
  /** Provider endpoint root for BYOK empty-response 排查包 (never the API key). */
  base_url?: string;
  /** 上游 429 Retry-After 秒数（原始值；工程重试仍截断 ≤30s）。 */
  retry_after?: number;
  /** 上游额度恢复的绝对时刻（ISO-8601 UTC，如 2026-08-14T16:00:00Z）；文案不含时刻，由客户端按本机时区渲染。 */
  recovery_at?: string;
  /** 平台配额窗口翻篇的绝对时刻（ISO-8601 UTC）；同 recovery_at 由客户端本地化。 */
  reset_at?: string;
  /** LLM_KEY_INVALID CTA 分流：user=各端换 Key（桌面「去服务商」、手机「去配置」）；platform=接入自己的 Key / 联系管理员。 */
  credential_source?: string;
  /** 上游 vendor 子码（message 方括号或 error.code），供排查包定位 tool schema 拒绝。 */
  vendor_code?: string;
  /** 本轮请求的模型 id。 */
  model?: string;
  /** 本轮 scenario / 推理 profile 名（chat / agent / …）。 */
  profile?: string;
  /** 本轮发给上游的 tools 条数。 */
  tool_count?: number;
}

export interface ErrorPayload {
  code: string;
  message: string;
  context?: ErrorContext;
}

export interface TitleGeneratedPayload {
  conversation_id: string;
  title: string;
}

/** BYOK soft gate: preflight hint when probe says the user's model may lack tool
 * calling. Transport-only — not journaled. */
export interface TurnWarningPayload {
  message: string;
}

/** 团队浏览器直播通道状态（`browser_live_status`）：`started` 有会话且开播；
 * `no_session` 附着但无直播会话；`session_closed` 观看中的会话被回收/关闭。 */
export type BrowserLiveState = "started" | "no_session" | "session_closed";

/** One live screencast frame on `browser_live_frame`（base64 jpeg + 设备像素尺寸）. */
export interface BrowserLiveFramePayload {
  frame_b64: string;
  width: number;
  height: number;
}

/** Live channel status on ``browser_live_status`` (D14).
 * 
 * ``started`` — a live browser session exists and screencast is now flowing to viewers;
 * ``no_session`` — the viewer attached but the conversation has no live browser session;
 * ``session_closed`` — the watched session was recycled / closed (idle only when unwatched,
 * or max-lifetime). */
export interface BrowserLiveStatusPayload {
  state: BrowserLiveState;
}

export interface TurnSavedPayload {
  user_message_id: string;
}

export interface Citation {
  url: string;
  title: string;
  snippet?: string;
  site?: string;
  id?: string;
  date?: string;
  tier?: string;
  query?: string;
  deep_read?: boolean;
  registrant?: string;
  citable?: boolean;
}

export interface CitationsPayload {
  citations: Citation[];
}

/** Transport-only client-tool request: apply a workspace file op on the bound
 * desktop and POST the result back. NOT journaled.
 * 
 * ``timeout_ms`` (optional): liveness budget echoed from the server channel so the
 * desktop can AbortSignal the IPC op; derived from the outer tool deadline. */
export interface WorkspaceOpRequiredPayload {
  request_id: string;
  conversation_id: string;
  root_id: string;
  op: string;
  args: Record<string, unknown>;
  timeout_ms?: number;
}

/** One structured whiteboard op (AI协作白板 M2). The closed verb set is shared with
 * the server tool + the desktop applier; fields beyond `op` are op-specific. */
export interface BoardOp {
  op: "add_node" | "connect" | "move" | "set_text" | "delete" | "group";
  ref?: string;
  id?: string;
  kind?: "sticky" | "rectangle" | "ellipse" | "diamond" | "text";
  text?: string;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  color?: string;
  from?: string;
  to?: string;
  label?: string;
  members?: string[];
}

/** Transport-only client-tool request: apply a batch of board ops to the open
 * whiteboard canvas (`board_id`). The board counterpart of `workspace_op_required`;
 * NOT journaled. */
export interface BoardOpRequiredPayload {
  request_id: string;
  conversation_id: string;
  board_id: string;
  ops: BoardOp[];
  summary: string;
}

/** Transport-only client-tool request: rasterize board elements (`ids`) to a PNG and
 * POST it back so the vision reader can read it. NOT journaled. */
export interface BoardReadRequiredPayload {
  request_id: string;
  conversation_id: string;
  board_id: string;
  ids: string[];
}

/** Transport-only client-tool request: show an OS notification on the bound desktop
 * (`desktop_notify` worker tool). NOT journaled. */
export interface DesktopNotifyRequiredPayload {
  request_id: string;
  conversation_id: string;
  title: string;
  body?: string;
}

/** Transport-only client-tool request: silently mount a local directory read-only
 * (`external_mount_readonly`). Path transport exception — may carry `path` /
 * `well_known`+`target_name` for desktop resolve; success result must not include abs.
 * NOT journaled. */
export interface ExternalMountReadonlyRequiredPayload {
  request_id: string;
  conversation_id: string;
  path?: string;
  well_known?: string;
  target_name?: string;
}

/** Transport-only client-tool request: run a Host op on the bound desktop
 * (`host_*` tools). NOT journaled. */
export interface HostOpRequiredPayload {
  request_id: string;
  conversation_id: string;
  op: string;
  args?: Record<string, unknown>;
}

/** Transport-only client-tool request: run a local MCP Client op on the bound
 * desktop (stdio list_tools / call_tool). NOT journaled. */
export interface McpOpRequiredPayload {
  request_id: string;
  conversation_id: string;
  op: string;
  args?: Record<string, unknown>;
}

/** 裸聊写盘自动建的云文件夹（双模式工作区 §5.4 裸聊行）——告知落点，不改会话归属。
 * 
 * ``name`` 是建桌那一刻的名字；用户当场改名后客户端以文件夹现名为准（按 ``folder_id``
 * 查），本 payload 不追改名。 */
export interface AutoFolderCreatedPayload {
  folder_id: string;
  name: string;
}

export interface HandoffSnapshotDonePayload {
  snapshot_id: string;
  conversation_id: string;
  size_bytes: number;
}

export interface HandoffJobStartedPayload {
  job_id: string;
  conversation_id: string;
  job_conversation_id: string;
}

export interface HandoffApplyResult {
  path: string;
  status: "applied" | "skipped" | "conflict" | "error";
  change_type: "added" | "modified" | "deleted" | null;
  detail: string;
}

export interface HandoffApplyDonePayload {
  job_id: string;
  conversation_id: string;
  results: HandoffApplyResult[];
  applied: number;
  skipped: number;
  conflicts: number;
  errors: number;
}

/** Post-turn auto-backup succeeded (EPHEMERAL — clears failure UX). */
export interface WorkspaceSnapshotDonePayload {
  snapshot_id: string;
  conversation_id: string;
  size_bytes: number;
}

/** Post-turn auto-backup failed (EPHEMERAL — toast / panel banner; no error detail). */
export interface WorkspaceSnapshotFailedPayload {
  conversation_id: string;
}

export type SSEPayloadMap = {
  message_start: MessageStartPayload;
  content_delta: ContentDeltaPayload;
  content_reset: ContentResetPayload;
  reasoning_delta: ReasoningDeltaPayload;
  tool_progress: ToolProgressPayload;
  tool_use_progress: ToolUseProgressPayload;
  tool_use_start: ToolUseStartPayload;
  tool_use_end: ToolUseEndPayload;
  approval_required: ApprovalRequiredPayload;
  approval_resolved: ApprovalResolvedPayload;
  checkpoint_required: CheckpointRequiredPayload;
  checkpoint_resolved: CheckpointResolvedPayload;
  plan_review_required: PlanReviewRequiredPayload;
  plan_review_resolved: PlanReviewResolvedPayload;
  stage_card_required: StageCardRequiredPayload;
  stage_card_resolved: StageCardResolvedPayload;
  plan_revised: PlanRevisedPayload;
  run_plan: RunPlanPayload;
  graph_append: GraphAppendPayload;
  run_started: RunStartedPayload;
  run_context: RunContextPayload;
  run_output_delta: RunOutputDeltaPayload;
  run_output_reset: RunOutputResetPayload;
  run_reasoning_delta: RunReasoningDeltaPayload;
  run_tool_progress: RunToolProgressPayload;
  run_phase: RunPhasePayload;
  run_completed: RunCompletedPayload;
  run_failed: RunFailedPayload;
  run_cancelled: RunCancelledPayload;
  run_skipped: RunSkippedPayload;
  run_progress: RunProgressPayload;
  batch_metrics: BatchMetricsPayload;
  run_escalation: RunEscalationPayload;
  run_escalation_gate: RunEscalationGatePayload;
  escalation_required: EscalationRequiredPayload;
  escalation_resolved: EscalationResolvedPayload;
  interaction_orphaned: InteractionOrphanedPayload;
  team_synthesis_preview: TeamSynthesisPreviewPayload;
  coordination_wait: CoordinationWaitPayload;
  workspace_lock_wait: WorkspaceLockWaitPayload;
  delivery_status: DeliveryStatusPayload;
  user_interjection: UserInterjectionPayload;
  turn_queued: TurnQueuedPayload;
  turn_queue_started: TurnQueueStartedPayload;
  turn_queue_cancelled: TurnQueueCancelledPayload;
  resume_deferred: ResumeDeferredPayload;
  resume_settled: ResumeSettledPayload;
  execution_detached: ExecutionDetachedPayload;
  execution_completed: ExecutionCompletedPayload;
  debate_result: DebateResultPayload;
  debate_round_started: DebateRoundStartedPayload;
  debate_round: DebateRoundPayload;
  debate_pretrial_started: DebatePretrialStartedPayload;
  debate_pretrial_orders: DebatePretrialOrdersPayload;
  debate_pretrial_completed: DebatePretrialCompletedPayload;
  message_end: MessageEndPayload;
  error: ErrorPayload;
  title_generated: TitleGeneratedPayload;
  turn_warning: TurnWarningPayload;
  browser_live_frame: BrowserLiveFramePayload;
  browser_live_status: BrowserLiveStatusPayload;
  turn_saved: TurnSavedPayload;
  citations: CitationsPayload;
  evidence_ledger: EvidenceLedgerPayload;
  workspace_op_required: WorkspaceOpRequiredPayload;
  board_op_required: BoardOpRequiredPayload;
  board_read_required: BoardReadRequiredPayload;
  desktop_notify_required: DesktopNotifyRequiredPayload;
  external_mount_readonly_required: ExternalMountReadonlyRequiredPayload;
  host_op_required: HostOpRequiredPayload;
  mcp_op_required: McpOpRequiredPayload;
  auto_folder_created: AutoFolderCreatedPayload;
  handoff_snapshot_done: HandoffSnapshotDonePayload;
  handoff_job_started: HandoffJobStartedPayload;
  handoff_apply_done: HandoffApplyDonePayload;
  workspace_snapshot_done: WorkspaceSnapshotDonePayload;
  workspace_snapshot_failed: WorkspaceSnapshotFailedPayload;
};
