// AUTO-GENERATED by apps/server/scripts/dump_interaction_kinds.py — do not edit.
// Single source: agentcore.runtime.interaction.InteractionKind + INTERACTION_KIND_SPECS
// Regenerate: pnpm gen:types  (or uv run python scripts/dump_interaction_kinds.py)

/** Full bridge enum (includes client_tool). */
export type InteractionKind =
  | "approval"
  | "ask_user"
  | "client_tool"
  | "escalation"
  | "plan_review"
  | "stage_card";

export const INTERACTION_KIND_VALUES = [
  "approval",
  "ask_user",
  "client_tool",
  "escalation",
  "plan_review",
  "stage_card",
] as const;

/** User-facing decision / ask kinds (InteractionStore + journal fold). */
export type UserInteractionKind =
  | "approval"
  | "ask_user"
  | "escalation"
  | "plan_review"
  | "stage_card";

export const USER_INTERACTION_KIND_VALUES = [
  "approval",
  "ask_user",
  "escalation",
  "plan_review",
  "stage_card",
] as const;

export type InteractionKindWire = {
  readonly requiredEvent: string;
  readonly resolvedEvent: string | null;
  readonly idField: string;
  readonly hot: boolean;
  readonly pausesTurn: boolean;
  readonly reconnectAnswerable: boolean;
  readonly journalSurface: boolean;
  readonly attention: boolean;
};

/** kind → SSE wire + behavior flags (hot / gate / recovery / journal / attention). */
export const INTERACTION_KIND_WIRE: Readonly<Record<UserInteractionKind, InteractionKindWire>> = {
  "approval": {
    requiredEvent: "approval_required",
    resolvedEvent: "approval_resolved",
    idField: "approval_id",
    hot: true,
    pausesTurn: true,
    reconnectAnswerable: true,
    journalSurface: true,
    attention: true,
  },
  "ask_user": {
    requiredEvent: "checkpoint_required",
    resolvedEvent: "checkpoint_resolved",
    idField: "checkpoint_id",
    hot: false,
    pausesTurn: true,
    reconnectAnswerable: false,
    journalSurface: true,
    attention: true,
  },
  "escalation": {
    requiredEvent: "escalation_required",
    resolvedEvent: "escalation_resolved",
    idField: "escalation_id",
    hot: true,
    pausesTurn: false,
    reconnectAnswerable: true,
    journalSurface: true,
    attention: true,
  },
  "plan_review": {
    requiredEvent: "plan_review_required",
    resolvedEvent: "plan_review_resolved",
    idField: "checkpoint_id",
    hot: false,
    pausesTurn: true,
    reconnectAnswerable: false,
    journalSurface: true,
    attention: true,
  },
  "stage_card": {
    requiredEvent: "stage_card_required",
    resolvedEvent: "stage_card_resolved",
    idField: "stage_card_id",
    hot: false,
    pausesTurn: false,
    reconnectAnswerable: true,
    journalSurface: true,
    attention: false,
  },
};
