"""SSE event type definitions and EventSink.

Events flow from the engine → asyncio.Queue → SSE StreamingResponse → client.
The EventSink decouples execution from delivery (backpressure-safe).

→ 见设计: docs/03-AI核心/执行引擎架构设计.md §二（SSE 事件协议）
"""

from __future__ import annotations

from agentcore.runtime.events.board import board_op_required, board_read_required
from agentcore.runtime.events.browser import browser_live_frame, browser_live_status
from agentcore.runtime.events.chat import (
    citations_event,
    content_delta,
    content_reset,
    error_event,
    evidence_ledger_event,
    message_end,
    message_start,
    reasoning_delta,
    title_generated,
    tool_progress,
    tool_use_end,
    tool_use_progress,
    tool_use_start,
    turn_saved,
    turn_warning,
)
from agentcore.runtime.events.conversation_hub import (
    ConversationStreamHub,
    ConversationWatcher,
    conversation_streams,
    publish_conversation_signal,
)
from agentcore.runtime.events.debate import (
    debate_pretrial_completed,
    debate_pretrial_orders,
    debate_pretrial_started,
    debate_result,
    debate_round,
    debate_round_started,
)
from agentcore.runtime.events.desktop import (
    desktop_notify_required,
    external_mount_readonly_required,
    host_op_required,
    mcp_op_required,
)
from agentcore.runtime.events.interaction import (
    approval_required,
    approval_resolved,
    checkpoint_required,
    checkpoint_resolved,
    escalation_required,
    escalation_resolved,
    interaction_orphaned,
    plan_review_required,
    plan_review_resolved,
    stage_card_required,
    stage_card_resolved,
)
from agentcore.runtime.events.journal_config import (
    _JOURNAL_EVENT_TYPES,
    _JOURNAL_SURFACE_TYPES,
)
from agentcore.runtime.events.resume import resume_deferred, resume_settled
from agentcore.runtime.events.run import (
    batch_metrics,
    coordination_wait,
    delivery_status,
    escalation_raised,
    execution_completed,
    execution_detached,
    graph_append,
    plan_revised,
    run_cancelled,
    run_completed,
    run_context,
    run_escalation_gate,
    run_failed,
    run_output_delta,
    run_output_reset,
    run_phase,
    run_plan,
    run_progress,
    run_reasoning_delta,
    run_skipped,
    run_started,
    run_tool_progress,
    team_note_posted,
    team_synthesis_preview,
    turn_queue_cancelled,
    turn_queue_started,
    turn_queued,
    user_interjection,
    workspace_lock_wait,
)
from agentcore.runtime.events.sink import EventSink, SinkSubscription
from agentcore.runtime.events.types import EventType, FinishReason, SSEEvent
from agentcore.runtime.events.workspace import (
    auto_folder_created,
    handoff_apply_done,
    handoff_job_started,
    handoff_snapshot_done,
    workspace_op_required,
    workspace_snapshot_done,
    workspace_snapshot_failed,
)

__all__ = [
    "EventType",
    "FinishReason",
    "SSEEvent",
    "EventSink",
    "SinkSubscription",
    "ConversationStreamHub",
    "ConversationWatcher",
    "conversation_streams",
    "publish_conversation_signal",
    "_JOURNAL_EVENT_TYPES",
    "_JOURNAL_SURFACE_TYPES",
    "message_start",
    "content_delta",
    "content_reset",
    "reasoning_delta",
    "tool_progress",
    "tool_use_progress",
    "tool_use_start",
    "tool_use_end",
    "citations_event",
    "evidence_ledger_event",
    "approval_required",
    "approval_resolved",
    "checkpoint_required",
    "checkpoint_resolved",
    "plan_review_required",
    "plan_review_resolved",
    "stage_card_required",
    "stage_card_resolved",
    "workspace_op_required",
    "board_op_required",
    "board_read_required",
    "browser_live_frame",
    "browser_live_status",
    "desktop_notify_required",
    "external_mount_readonly_required",
    "host_op_required",
    "mcp_op_required",
    "auto_folder_created",
    "handoff_snapshot_done",
    "handoff_job_started",
    "handoff_apply_done",
    "workspace_snapshot_done",
    "workspace_snapshot_failed",
    "message_end",
    "error_event",
    "title_generated",
    "turn_saved",
    "turn_warning",
    "run_plan",
    "graph_append",
    "plan_revised",
    "run_started",
    "run_context",
    "run_output_delta",
    "run_output_reset",
    "run_reasoning_delta",
    "run_phase",
    "run_tool_progress",
    "escalation_raised",
    "escalation_required",
    "escalation_resolved",
    "interaction_orphaned",
    "run_escalation_gate",
    "team_note_posted",
    "team_synthesis_preview",
    "coordination_wait",
    "workspace_lock_wait",
    "delivery_status",
    "user_interjection",
    "turn_queued",
    "turn_queue_started",
    "turn_queue_cancelled",
    "resume_deferred",
    "resume_settled",
    "execution_detached",
    "execution_completed",
    "run_completed",
    "run_failed",
    "run_cancelled",
    "run_skipped",
    "run_progress",
    "batch_metrics",
    "debate_result",
    "debate_round_started",
    "debate_round",
    "debate_pretrial_started",
    "debate_pretrial_orders",
    "debate_pretrial_completed",
]
