#!/usr/bin/env node
/**
 * 构建前发现 Latest（品牌域 desktop/stable|beta/latest.json → 版本；安装包 URL 构造为 GitHub Releases），
 * 生成 download.generated.ts。线上 /download 还会经 Pages Function
 * /api/desktop-release 再拉一次；此脚本仅作 SSG 首屏与 metadata 回退。
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  artifactUrlsForVersion,
  fetchLatestReleaseArtifacts,
} from "../functions/_lib/releaseArtifacts.mjs";

const FALLBACK_VERSION = "0.9.9";
/** 测试版 SSG 回退；空 = 无 beta CDN 时不生成测试版按钮 URL。 */
const FALLBACK_BETA_VERSION = "";

const __dir = dirname(fileURLToPath(import.meta.url));

async function main() {
  let artifacts = {
    ...artifactUrlsForVersion(FALLBACK_VERSION),
    androidUrl: "",
    androidFilename: "",
    androidVersion: "",
    beta: null,
  };
  try {
    artifacts = await fetchLatestReleaseArtifacts(
      FALLBACK_VERSION,
      FALLBACK_BETA_VERSION,
    );
    const parts = ["win"];
    if (artifacts.macUrl) parts.push("mac");
    if (artifacts.androidUrl) parts.push("android");
    console.log(
      `fetch-release: stable v${artifacts.version}` +
        (artifacts.beta?.version ? ` · beta v${artifacts.beta.version}` : "") +
        (artifacts.androidVersion
          ? ` · android v${artifacts.androidVersion}`
          : "") +
        ` (${parts.join("+")})`,
    );
  } catch (err) {
    console.warn(
      `fetch-release: ${err instanceof Error ? err.message : err} — fallback v${FALLBACK_VERSION}`,
    );
  }

  const beta = artifacts.beta;
  const out = `/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-release.mjs — do not edit.
export const DESKTOP_VERSION = ${JSON.stringify(artifacts.version)};
export const RELEASE_NOTES_URL = ${JSON.stringify(artifacts.releaseNotesUrl)};
export const WIN_INSTALLER_URL = ${JSON.stringify(artifacts.winUrl)};
export const WIN_INSTALLER_FILENAME = ${JSON.stringify(artifacts.winFilename)};
export const MAC_DMG_URL = ${JSON.stringify(artifacts.macUrl)};
export const MAC_DMG_FILENAME = ${JSON.stringify(artifacts.macFilename)};
export const ANDROID_APK_URL = ${JSON.stringify(artifacts.androidUrl)};
export const ANDROID_APK_FILENAME = ${JSON.stringify(artifacts.androidFilename)};
export const ANDROID_VERSION = ${JSON.stringify(artifacts.androidVersion)};
export const BETA_DESKTOP_VERSION = ${JSON.stringify(beta?.version ?? "")};
export const BETA_RELEASE_NOTES_URL = ${JSON.stringify(beta?.releaseNotesUrl ?? "")};
export const BETA_WIN_INSTALLER_URL = ${JSON.stringify(beta?.winUrl ?? "")};
export const BETA_WIN_INSTALLER_FILENAME = ${JSON.stringify(beta?.winFilename ?? "")};
export const BETA_MAC_DMG_URL = ${JSON.stringify(beta?.macUrl ?? "")};
export const BETA_MAC_DMG_FILENAME = ${JSON.stringify(beta?.macFilename ?? "")};
`;

  writeFileSync(join(__dir, "../src/lib/download.generated.ts"), out, "utf8");
}

main();
