"""Generate ``packages/contract-types/src/interactionKinds.generated.ts``.

Single source: ``agentcore.runtime.interaction.InteractionKind`` +
``INTERACTION_KIND_SPECS`` (user-facing wire table).

Run as part of ``pnpm gen:types`` (or standalone)::

    uv run python scripts/dump_interaction_kinds.py
"""

from __future__ import annotations

from pathlib import Path

from agentcore.runtime.interaction import INTERACTION_KIND_SPECS, InteractionKind


def _ts_bool(value: bool) -> str:
    return "true" if value else "false"


HEADER = """\
// AUTO-GENERATED by apps/server/scripts/dump_interaction_kinds.py — do not edit.
// Single source: agentcore.runtime.interaction.InteractionKind + INTERACTION_KIND_SPECS
// Regenerate: pnpm gen:types  (or uv run python scripts/dump_interaction_kinds.py)
"""


def main() -> None:
    all_kinds = sorted(e.value for e in InteractionKind)
    wire_kinds = sorted(k.value for k in INTERACTION_KIND_SPECS)

    lines: list[str] = [HEADER.rstrip(), ""]
    lines.append("/** Full bridge enum (includes client_tool). */")
    lines.append("export type InteractionKind =")
    for v in all_kinds:
        lines.append(f'  | "{v}"')
    lines[-1] = f"{lines[-1]};"
    lines.append("")

    lines.append("export const INTERACTION_KIND_VALUES = [")
    for v in all_kinds:
        lines.append(f'  "{v}",')
    lines.append("] as const;")
    lines.append("")

    lines.append(
        "/** User-facing decision / ask kinds (InteractionStore + journal fold). */"
    )
    lines.append("export type UserInteractionKind =")
    for v in wire_kinds:
        lines.append(f'  | "{v}"')
    lines[-1] = f"{lines[-1]};"
    lines.append("")

    lines.append("export const USER_INTERACTION_KIND_VALUES = [")
    for v in wire_kinds:
        lines.append(f'  "{v}",')
    lines.append("] as const;")
    lines.append("")

    lines.append("export type InteractionKindWire = {")
    lines.append("  readonly requiredEvent: string;")
    lines.append("  readonly resolvedEvent: string | null;")
    lines.append("  readonly idField: string;")
    lines.append("  readonly hot: boolean;")
    lines.append("  readonly pausesTurn: boolean;")
    lines.append("  readonly reconnectAnswerable: boolean;")
    lines.append("  readonly journalSurface: boolean;")
    lines.append("  readonly attention: boolean;")
    lines.append("};")
    lines.append("")

    lines.append(
        "/** kind → SSE wire + behavior flags (hot / gate / recovery / journal / attention). */"
    )
    lines.append(
        "export const INTERACTION_KIND_WIRE: "
        "Readonly<Record<UserInteractionKind, InteractionKindWire>> = {"
    )
    for kind in sorted(INTERACTION_KIND_SPECS.keys(), key=lambda k: k.value):
        spec = INTERACTION_KIND_SPECS[kind]
        resolved = (
            "null" if spec.resolved_event is None else f'"{spec.resolved_event}"'
        )
        lines.append(f'  "{kind.value}": {{')
        lines.append(f'    requiredEvent: "{spec.required_event}",')
        lines.append(f"    resolvedEvent: {resolved},")
        lines.append(f'    idField: "{spec.id_field}",')
        lines.append(f"    hot: {_ts_bool(spec.hot)},")
        lines.append(f"    pausesTurn: {_ts_bool(spec.pauses_turn)},")
        lines.append(f"    reconnectAnswerable: {_ts_bool(spec.reconnect_answerable)},")
        lines.append(f"    journalSurface: {_ts_bool(spec.journal_surface)},")
        lines.append(f"    attention: {_ts_bool(spec.attention)},")
        lines.append("  },")
    lines.append("};")
    lines.append("")

    content = "\n".join(lines)
    out = (
        Path(__file__).resolve().parents[3]
        / "packages"
        / "contract-types"
        / "src"
        / "interactionKinds.generated.ts"
    )
    out.write_text(content, encoding="utf-8")
    print(
        f"wrote {out} ({len(all_kinds)} kinds, {len(wire_kinds)} user-facing wire)"
    )


if __name__ == "__main__":
    main()
